---
- hosts:
    - localhost
    - all
  sudo: yes
  tasks:
    - name: yum update
      yum: name=* state=latest
    - name: disable iptables
      service: name=iptables state=stopped enabled=no
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: remove localtime
      file: path=/etc/localtime state=absent
    - name: change timezone
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644
    - name: change locale
      command: sed -i "s/en_US/ja_JP/g" /etc/sysconfig/i18n
    - name: install remi repository
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present
    - name: install man
      yum: name=man state=latest
    - name: install git
      yum: name=git state=latest
    - name: install tig
      yum: name=tig state=latest
    - name: install vim
      yum: name=vim state=latest
    - name: install unzip
      yum: name=unzip state=latest

- hosts: sandbox
  vars:
    ACTIVATOR_VERSION: 1.3.6
  sudo: yes
  tasks:
    - name: install java
      yum: name=java-1.8.0-openjdk-devel.x86_64 state=latest
    - name: get activator
      get_url: url=http://downloads.typesafe.com/typesafe-activator/{{ ACTIVATOR_VERSION }}/typesafe-activator-{{ ACTIVATOR_VERSION }}.zip dest=/tmp/typesafe-activator-{{ ACTIVATOR_VERSION }}.zip
    - name: unzip activator.zip
      unarchive: src=/tmp/typesafe-activator-{{ ACTIVATOR_VERSION }}.zip dest=/opt copy=no mode=0777
    - name: ln activator
      file: src=/opt/activator-dist-{{ ACTIVATOR_VERSION }}/activator dest=/usr/local/bin/activator state=link force=yes
